dist: xenial
language: bash
services: docker
matrix:
  include:
    # Fedora container image repository
    # * Docker Hub: fedora
    #   https://hub.docker.com/_/fedora
    # * Fedora official container repository. But it's slow to download.
    #   https://registry.fedoraproject.org/repo/fedora/tags/
    # Intel, 64-bit, Little-endian
    - name: x86_64
      env: BASE_IMAGE=fedora
    # ARM, 64-bit, Little-endian
    - name: aarch64
      env: BASE_IMAGE=arm64v8/fedora
    # ARM, 32-bit, Little-endian
    - name: armv7hl
      env: BASE_IMAGE=arm32v7/fedora

    # As "arm32v7/fedora" case has an error, "arm32v7/fedora:26" is
    # the temporary workflow of arm32.
    # arm32v7/fedora:27, 28, 29 do not work with the error message
    # "Error: Failed to synchronize cache for repo 'fedora'".
    - name: armv7hl-26
      env: BASE_IMAGE=arm32v7/fedora:26
    # armv7hl: failed to install with error: unpacking of archive failed on file.
    # https://bugzilla.redhat.com/show_bug.cgi?id=1738233
    # - name: armv7hl-31-official-repo
    #   env: BASE_IMAGE=registry.fedoraproject.org/fedora:31-armhfp

    # IBM PowerPC, 64-bit, Little-endian
    - name: ppc64le
      env: BASE_IMAGE=ppc64le/fedora
    # IBM Z and LinuxONE, 64-bit, Big-endian
    - name: s390x
      env: BASE_IMAGE=s390x/fedora

    # ====================
    # Advanced ways
    - name: "Advanced: podman-aarch64"
      addons:
        apt:
          packages:
            - podman
          sources:
            # podman and some container tools.
            # https://github.com/containers/libpod/blob/master/install.md
            - sourceline: "ppa:projectatomic/ppa"
      before_install:
        - podman --version
        - podman version
        - podman info --debug
      install:
        # Incompatibilities of podman from docker on Travis CI
        # https://github.com/containers/libpod/issues/3679
        - ci/patch_podman.sh

        - sudo podman --log-level debug pull multiarch/qemu-user-static
        - sudo podman --log-level debug run --rm --privileged multiarch/qemu-user-static --reset -p yes
        # - sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - podman build --rm --build-arg BASE_IMAGE="${BASE_IMAGE}" -t my-fedora .
      script:
        - podman run --rm -t my-fedora bash -cx "uname -m && make clean test"

    # "docker build --platform PLATFORM" works on Fedora environment.
    # https://github.com/containers/buildah/issues/1590#issuecomment-517225516
    # But it does not work on Travis CI for now.
    - name: "Advanced: docker-build-platform-aarch64"
      env: PLATFORM=linux/arm64
      install:
        - ci/install_latest_docker.sh

        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - DOCKER_BUILDKIT=1 docker build -t my-fedora --platform "${PLATFORM}" .

    # See below ticket for other architectures.
    # Supporting target platform: "ppc64le" and "s390x"
    # https://github.com/docker/buildx/issues/115
    - name: "Advanced: docker-buildx-build-platform-aarch64"
      env: PLATFORM=linux/arm64
      install:
        - ci/install_latest_docker.sh
        - ci/install_docker_buildx.sh

        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - docker buildx build --rm -t my-fedora:aarch64 --platform "${PLATFORM}" .
    # ====================
  allow_failures:
    # Error: Incorrect or unknown "arch": armv7hcnl
    # https://bugzilla.redhat.com/show_bug.cgi?id=1691430#c6
    - name: armv7hl
    - name: "Advanced: podman-aarch64"
    - name: "Advanced: docker-build-platform-aarch64"
    - name: "Advanced: docker-buildx-build-platform-aarch64"
  fast_finish: true
before_install:
  - docker --version
  - docker version
  - docker info
install:
  - ls /proc/sys/fs/binfmt_misc/
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - ls /proc/sys/fs/binfmt_misc/
  - docker build --rm --build-arg BASE_IMAGE="${BASE_IMAGE}" -t my-fedora .
script:
  - docker run --rm -t my-fedora bash -cx "uname -m && make clean test"
branches:
  only:
    - master
