dist: xenial
language: bash
services: docker
matrix:
  include:
    # Fedora container image repository
    # * Docker Hub: fedora
    #   https://hub.docker.com/_/fedora
    # * Fedora official container repository. But it's slow to download.
    #   https://registry.fedoraproject.org/
    - name: x86_64
      env: BASE_IMAGE=fedora
    - name: aarch64
      env: BASE_IMAGE=arm64v8/fedora
    - name: arm32
      env: BASE_IMAGE=arm32v7/fedora
    - name: ppc64le
      env: BASE_IMAGE=ppc64le/fedora
    - name: s390x
      env: BASE_IMAGE=s390x/fedora

    # ====================
    # Advanced ways
    - name: "Advanced: docker-build-platform-aarch64"
      env: PLATFORM=linux/arm64
      install:
        - ci/install_latest_docker.sh

        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - DOCKER_BUILDKIT=1 docker build -t my-fedora --platform "${PLATFORM}" .

    # See https://github.com/docker/buildx/issues/115 to detect other architectures.
    - name: "Advanced: docker-buildx-platform-aarch64"
      env: PLATFORM=linux/arm64
      install:
        - ci/install_latest_docker.sh
        - ci/install_docker_buildx.sh

        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - docker buildx build --rm -t my-fedora:aarch64 --platform "${PLATFORM}" .

    - name: "Advanced: podman-aarch64"
      addons:
        apt:
          packages:
            - podman
          sources:
            # podman and some container tools.
            # https://github.com/containers/libpod/blob/master/install.md
            - sourceline: "ppa:projectatomic/ppa"
      before_install:
        - podman --version
        - podman version
        - podman info --debug
      install:
        # Incompatibilities of podman from docker on Travis CI
        # https://github.com/containers/libpod/issues/3679
        - ci/patch_podman.sh

        - sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - podman build --rm --build-arg BASE_IMAGE="${BASE_IMAGE}" -t my-fedora .
      script:
        - podman run --rm -t my-fedora bash -cx "uname -m && make clean test"
    # ====================
  allow_failures:
    # Error: Incorrect or unknown "arch": armv7hcnl
    # https://bugzilla.redhat.com/show_bug.cgi?id=1691430#c6
    - name: arm32
    - name: "Advanced: docker-build-platform-aarch64"
    - name: "Advanced: docker-buildx-platform-aarch64"
    - name: "Advanced: podman-aarch64"
  fast_finish: true
before_install:
  - docker --version
  - docker version
  - docker info
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker build --rm --build-arg BASE_IMAGE="${BASE_IMAGE}" -t my-fedora .
script:
  - docker run --rm -t my-fedora bash -cx "uname -m && make clean test"
branches:
  only:
    - master
