dist: xenial
language: bash
services: docker
git:
  quiet: true
addons:
  apt:
    config:
      retries: true
      update: true
      sources:
        # To install podman, and other optional useful packages.
        # https://github.com/containers/libpod/blob/master/install.md
        - sourceline: 'ppa:projectatomic/ppa'
      packages:
        # repository: base
        - jq
        # repository: ppa:projectatomic/ppa
        - podman
        - buildah
        - skopeo
matrix:
  include:
    # Docker Hub: fedora
    # https://hub.docker.com/_/fedora
    # Fedora official container repository. But it's slow to download.
    # https://registry.fedoraproject.org/
    - env: BASE_IMAGE=fedora
    - env: BASE_IMAGE=arm64v8/fedora
    - env: BASE_IMAGE=ppc64le/fedora
    - env: BASE_IMAGE=s390x/fedora
before_install:
  - podman --version
  - docker --version
install:
  - sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - ls /proc/sys/fs/binfmt_misc/
  - podman build --rm -t my-fedora .
script:
  - |
    podman run --rm -t my-fedora bash -cx "
uname -m && cd 01.basic && make clean && make && make test
"
branches:
  only:
    - master
